[server]
maxUploadSize = 1000
[client]
showErrorDetails = false
toolbarMode = "viewer"

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[ui]
hideTopBar = true
